# Generated by Django 6.1.1 on 2026-09-14 16:48

import experiencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='imagen',
            field=models.ImageField(upload_to=experiencias.models.renombrar_imagen, verbose_name='Imagen'),
        ),
    ]
