# Generated by Django 6.1.1 on 2026-09-24 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias', '0003_categoria_estado_experiencia_estado_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencias.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='duracion',
            field=models.IntegerField(verbose_name='Duración'),
        ),
    ]
