# Generated by Django 6.1.1 on 2026-09-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('GUIA', 'Guia'), ('TURISTA', 'Turista')], default='TURISTA', max_length=10, verbose_name='Rol'),
        ),
    ]
