# Generated by Django 6.1.1 on 2026-10-07 17:19

import turismo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CulturaGastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CULTURA', 'Cultura y Tradición Llanera'), ('GASTRONOMIA', 'Gastronomía Típica')], default='CULTURA', max_length=20, verbose_name='Tipo de Publicación')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo o Resumen Corto')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('imagen', models.ImageField(upload_to=turismo.models.renombrar_cultura, verbose_name='Fotografía')),
                ('origen_region', models.CharField(default='Llanos Orientales', max_length=100, verbose_name='Región u Origen')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Destino')),
                ('departamento', models.CharField(choices=[('META', 'Meta'), ('CASANARE', 'Casanare'), ('ARAUCA', 'Arauca'), ('VICHADA', 'Vichada'), ('GUAVIARE', 'Guaviare')], default='META', max_length=20, verbose_name='Departamento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to=turismo.models.renombrar_destino, verbose_name='Fotografía Principal')),
                ('clima_promedio', models.CharField(default='28°C - Tropical Cálido', max_length=100, verbose_name='Clima Promedio')),
                ('atractivos', models.TextField(help_text='Separados por comas o viñetas', verbose_name='Atractivos Principales')),
                ('como_llegar', models.TextField(blank=True, null=True, verbose_name='Cómo Llegar')),
                ('destacado', models.BooleanField(default=False, verbose_name='Destacado en Portada')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado Activo')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono o WhatsApp')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje o Consulta')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Envío')),
                ('leido', models.BooleanField(default=False, verbose_name='Marcado como Leído')),
            ],
        ),
    ]
