# Generated by Django 6.1.1 on 2026-09-24 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiencias', '0004_alter_experiencia_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('numero_poliza', models.CharField(max_length=50, verbose_name='Número de Póliza')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de Expiración')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Reserva')),
                ('numero_personas', models.PositiveIntegerField(verbose_name='Número de Personas')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('peticiones_especiales', models.TextField(blank=True, null=True, verbose_name='Peticiones Especiales')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='experiencias.experiencia', verbose_name='Experiencia')),
                ('poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.polizaseguro', verbose_name='Póliza de Seguro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
